config/routes.rb
Rails.application.routes.draw do
  resources :pads
  
  root 'pads#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :pad
end

app/models/key.rb
class Key < ActiveRecord::Base
end

app/models/pad.rb
class Pad < ActiveRecord::Base
  has_many :images, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pads_controller.rb
class PadsController < ApplicationController
  before_action :set_pad, only: [:show, :edit, :update, :destroy]

  # GET /pads
  # GET /pads.json
  def index
    @pads = Pad.order("timestamp DESC").paginate(:page => params[:page], :per_page => 30)
  end

  # GET /pads/1
  # GET /pads/1.json
  def show
  end

  # GET /pads/new
  def new
    @pad = Pad.new
  end

  # GET /pads/1/edit
  def edit
  end

  # POST /pads
  # POST /pads.json
  def create
    @pad = Pad.new(pad_params)

    respond_to do |format|
      if @pad.save
        format.html { redirect_to @pad, notice: 'Pad was successfully created.' }
        format.json { render :show, status: :created, location: @pad }
      else
        format.html { render :new }
        format.json { render json: @pad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pads/1
  # PATCH/PUT /pads/1.json
  def update
    respond_to do |format|
      if @pad.update(pad_params)
        format.html { redirect_to @pad, notice: 'Pad was successfully updated.' }
        format.json { render :show, status: :ok, location: @pad }
      else
        format.html { render :edit }
        format.json { render json: @pad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pads/1
  # DELETE /pads/1.json
  def destroy
    @pad.destroy
    respond_to do |format|
      format.html { redirect_to pads_url, notice: 'Pad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pad
      @pad = Pad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pad_params
      params.require(:pad).permit(:heading, :body, :price, :external_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pads_helper.rb
module PadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Padlistings</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

<%= yield %>

</body>
</html>

app/views/pads/_form.html.erb
<%= form_for(@pad) do |f| %>
  <% if @pad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pad.errors.count, "error") %> prohibited this pad from being saved:</h2>

      <ul>
      <% @pad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :heading %><br>
    <%= f.text_field :heading %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :external_url %><br>
    <%= f.text_field :external_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pads/edit.html.erb
<h1>Editing pad</h1>

<%= render 'form' %>

<%= link_to 'Show', @pad %> |
<%= link_to 'Back', pads_path %>

app/views/pads/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Heading</th>
      <th>Price</th>
      <th>Timestamp</th>
      <th>URL</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pads.each do |pad| %>
      <tr>
        <td><%= pad.heading %></td>
        <td><%= number_to_currency(pad.price, precision: 0) %></td>
        <td><%= pad.timestamp.localtime %></td>
        <td><%= link_to pad.external_url, pad.external_url %></td>
        <td><%= link_to 'Show', pad %></td>
        <td><%= link_to 'Edit', edit_pad_path(pad) %></td>
        <td><%= link_to 'Destroy', pad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @pads, renderer: BootstrapPagination::Rails %>

<br>

<%= link_to 'New Pad', new_pad_path %>

app/views/pads/new.html.erb
<h1>New pad</h1>

<%= render 'form' %>

<%= link_to 'Back', pads_path %>

app/views/pads/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @pad.heading %></h1>

<p><%= @pad.body %></p>

<p><%= number_to_currency(@pad.price, precision: 0) %></p>

<p><%= link_to "View on Craigslist", @pad.external_url %></p>

<%= link_to 'Edit', edit_pad_path(@pad) %> |
<%= link_to 'Back', pads_path %>